apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-role-binding
  namespace: liberty-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-role
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: openshift-operators
