apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jpa20cdiwar # Name of the Argo CD application
  namespace: argocd # Argo CD namespace (or openshift-gitops if using OpenShift GitOps)
spec:
  destination:
    namespace: liberty-project # Namespace where the OpenLibertyApplication will be deployed
    server: https://kubernetes.default.svc # Kubernetes API server URL for the cluster
  project: default # Argo CD project to associate with this application
  source:
    repoURL: https://github.com/ShadyIBM/liberty.git # Your Git repository URL
    targetRevision: main # Git branch (e.g., main)
    path: apps/jpa20cdiwar/ # The directory where the OpenLibertyApplication YAML resides, not the specific file
  syncPolicy:
    automated:
      prune: true # Automatically delete resources not in the Git repository
      selfHeal: true # Automatically sync resources if they are manually modified in the cluster
