apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jpa20cdiwar # Name of the Argo CD application
  namespace: argocd # Argo CD namespace
spec:
  destination:
    namespace: liberty-project # The namespace in the cluster where OpenLibertyApplication will be deployed
    server: https://kubernetes.default.svc # Kubernetes cluster (current cluster)
  project: default # Default Argo CD project
  source:
    repoURL: https://github.com/ShadyIBM/liberty.git # Your Git repository URL
    targetRevision: main # The branch in your Git repository (e.g., main)
    path: apps/application-cr.yaml # The path to the directory containing the OpenLibertyApplication YAML file
  syncPolicy:
    automated:
      prune: true # Automatically remove resources that are deleted from the Git repository
      selfHeal: true # Automatically revert manual changes in the cluster to match the Git state
