apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpa20cdiwar
  namespace: liberty-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jpa20cdiwar
  template:
    metadata:
      labels:
        app: jpa20cdiwar
    spec:
      containers:
        - name: jpa20cdiwar
          image: quay.io/repository/shadyattia/jpa20cdiwar:v1
          ports:
            - containerPort: 9080
          envFrom:
            - configMapRef:
                name: my-app-config
